name = "Cobblemoon Lite"
author = "AZC Studios"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b075907180fc6f669b7b7cb9738131e7a771676475daa4c2945b187add141e0"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
