name = "Cobblemoon Lite"
author = "AZC Studios"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58e49d21e4b395192b8a0b55dcc160eebbc2489a139375e8bc68b1a15c05f127"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
