name = "Cobblemoon Lite"
author = "AZC Studios"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "765a830766e884256b741a96d920914a5f2745b6fbc921fa836fe24291b17f55"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
